import { Shield, Clock, Video, AlertTriangle, CheckCircle, XCircle } from 'lucide-react';

export const metadata = { title: 'Competition Rules — Cubelelo Events' };

const SECTIONS = [
  {
    icon: CheckCircle,
    color: 'text-emerald-400',
    bg: 'bg-emerald-400/10 border-emerald-400/20',
    title: 'Eligibility',
    rules: [
      'Open to all registered Cubelelo Events users. Free to create an account.',
      'Age no bar — juniors, seniors, and veterans are all welcome.',
      'You must be registered for a competition before the registration deadline to participate.',
      'One account per person. Duplicate accounts will be merged or removed.',
    ],
  },
  {
    icon: Clock,
    color: 'text-amber-400',
    bg: 'bg-amber-400/10 border-amber-400/20',
    title: 'Timing & Inspection',
    rules: [
      'All timing follows WCA regulations: 8-second free inspection, +2 penalty at 15 seconds, DNF at 17 seconds.',
      'The timer must be started using the spacebar (desktop) or two-finger touch (mobile).',
      'The built-in Cubelelo timer is the only accepted timing method — external timers are not permitted.',
      'Results are recorded to the nearest millisecond. Displayed times are truncated to hundredths.',
      'Solve windows are fixed. Submitting after the window closes will not be accepted.',
    ],
  },
  {
    icon: Shield,
    color: 'text-[#00dbe7]',
    bg: 'bg-[#00dbe7]/10 border-[#00dbe7]/20',
    title: 'Scrambles',
    rules: [
      'All scrambles are WCA-compliant random-state scrambles generated by cubing.js.',
      'Scrambles are revealed simultaneously to all competitors at round open.',
      'You must apply the scramble exactly as shown. Incorrect scramble application is your responsibility.',
      'Competitors are not permitted to view scrambles before the round officially opens.',
      'Scrambles cannot be regenerated or re-attempted once a solve is submitted.',
    ],
  },
  {
    icon: Video,
    color: 'text-purple-400',
    bg: 'bg-purple-400/10 border-purple-400/20',
    title: 'Video Verification',
    rules: [
      'All competitors must submit a video link (YouTube or Google Drive) after completing their solves.',
      'The video must show the scrambled state, the full solve, and the final solved state.',
      'The timer display must be visible in the video throughout the solve.',
      'Videos must be accessible (public or unlisted). Private videos cannot be reviewed.',
      'Failure to submit a valid video link may result in results being marked pending verification.',
    ],
  },
  {
    icon: AlertTriangle,
    color: 'text-red-400',
    bg: 'bg-red-400/10 border-red-400/20',
    title: 'Penalties & Disqualification',
    rules: [
      '+2: Cube not fully solved (one or more faces misaligned by more than 45°) at timer stop.',
      '+2: Inspection time exceeded (15–17 seconds).',
      'DNF: Inspection time exceeded beyond 17 seconds.',
      'DNF: Cube not in solved state. Any layer significantly misaligned counts as unsolved.',
      'Disqualification (DQ): Evidence of cheating, tampered scramble, or multiple valid submissions.',
      'Results flagged by our statistical system are reviewed by judges before being finalised.',
    ],
  },
  {
    icon: XCircle,
    color: 'text-orange-400',
    bg: 'bg-orange-400/10 border-orange-400/20',
    title: 'Fair Play',
    rules: [
      'You may not receive external assistance during a solve.',
      'Pre-inspection of the scrambled cube before inspection time begins is not permitted.',
      'Multiple accounts, score manipulation, or any form of cheating results in permanent ban.',
      'Judges review statistical outliers — results significantly faster than your history are flagged automatically.',
      'Appeals can be submitted within 24 hours of result publication. Admin decisions are final.',
    ],
  },
];

export default function Rules() {
  return (
    <div className="min-h-screen bg-[#0b0e11] text-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
        <div className="mb-10">
          <div className="flex items-center gap-2 mb-3">
            <Shield size={20} className="text-[#00dbe7]" />
            <h1 className="text-3xl font-black text-white">Competition Rules</h1>
          </div>
          <p className="text-[#8b949e]">
            All Cubelelo Events competitions follow WCA regulations unless stated otherwise.
            By registering for any competition, you agree to these rules.
          </p>
          <p className="text-xs text-[#8b949e] mt-2 font-mono">Last updated: June 2026</p>
        </div>

        <div className="space-y-6">
          {SECTIONS.map(({ icon: Icon, color, bg, title, rules }) => (
            <div key={title} className="bg-[#0d1117] border border-[#21262d] rounded-2xl overflow-hidden">
              <div className={`flex items-center gap-2 px-5 py-3 border-b border-[#21262d]`}>
                <div className={`w-7 h-7 rounded-lg border ${bg} flex items-center justify-center`}>
                  <Icon size={14} className={color} />
                </div>
                <h2 className="font-bold text-white text-sm">{title}</h2>
              </div>
              <ul className="p-5 space-y-3">
                {rules.map((rule, i) => (
                  <li key={i} className="flex gap-3 text-sm text-[#8b949e] leading-relaxed">
                    <span className={`font-mono text-xs ${color} mt-0.5 flex-shrink-0`}>{String(i + 1).padStart(2, '0')}</span>
                    <span>{rule}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="mt-10 p-5 bg-[#0d1117] border border-amber-500/20 rounded-2xl">
          <p className="text-xs text-amber-400 font-semibold mb-1">Note on rule updates</p>
          <p className="text-xs text-[#8b949e] leading-relaxed">
            Rules may be updated between competitions. The version in effect at the time of registration applies.
            Significant changes will be announced via the site banner and email notification.
          </p>
        </div>
      </div>
    </div>
  );
}
